name: mystiko_flutter

packages:
  - packages/**

scripts:
  quality-check:
    run: |
      melos run clean:deep && \
      melos clean && \
      melos bs && \
      melos run cargo:quality-check && \
      melos run dart:quality-check && \
      melos run flutter:quality-check
    description: Run all targets generally expected in CI for a full local quality check.

  clean:deep:
    run: git clean -x -d -f -q
    description: Clean things very deeply, can be used to establish "pristine checkout" status.

  bridge-codegen:
    run: |
      flutter_rust_bridge_codegen .flutter_rust_bridge.yaml && \
      melos run cargo:fmt && \
      melos run dart:format
    description: Generate flutter_rust_bridge code.

  cargo:quality-check:
    run: |
      melos run cargo:build && \
      melos run cargo:fmt && \
      melos run cargo:fmt-check && \
      melos run cargo:clippy && \
      melos run cargo:test
    description: Run Rust targets generally expected in CI for a full local quality check.
  cargo:build:
    run: cargo build -r
    description: Cargo Build rust module.
  cargo:fmt:
    run: cargo fmt --all
    description: Cargo Format rust module.
  cargo:fmt-check:
    run: cargo fmt --all -- --check
    description: Cargo Format Check rust module.
  cargo:clippy:
    run: cargo clippy --all-targets --all-features -j 4 -- -D warnings
    description: Cargo Clippy.
  cargo:test:
    run: cargo test
    description: Rust module run unit tests.

  dart:quality-check:
    run: |
      melos run dart:format && \
      melos run dart:check-format
    description: Run all static analysis checks.
  dart:format:
    exec: dart format .
    description: Format a specific package in this project.
  dart:check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.
  dart:test:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  flutter:quality-check:
    run: |
      melos run flutter:analyze
    description: Run all static analysis checks.
  flutter:analyze:
    exec: flutter analyze .
    description: Analyze a specific package in this project.
  flutter:test:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  build:
    run: melos run build:apple && melos run build:android && melos run build:other
    description: Build all native libraries for the project.

  build:apple:
    run: bash scripts/build-apple.sh
    description: Build the XCFramework for iOS and macOS.

  build:android:
    run: bash scripts/build-android.sh
    description: Build the .tar.gz for Android.

  build:other:
    run: bash scripts/build-other.sh
    description: Build the .tar.gz for all other platforms.

  test:
    run: melos run dart:test --no-select && melos run flutter:test --no-select
    description: Run all Dart & Flutter tests in this project.