name: mystiko_dart
description: A starting point for Dart libraries or applications.
version: 0.0.7
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: 1.82.6
  meta: ^1.8.0
  grpc: ^3.2.4
  mystiko_protos_dart:
    git:
      url: git@github.com:mystikonetwork/mystiko-protos-dart.git
      ref: f54efbf
  fixnum: ^1.1.0
  uuid: '>=3.0.6'
  logging: ^1.2.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.1.0
  test: ^1.24.0
